### ISSUE TITLE
Version of tensorflow used?

### ISSUE THREAD

**Issue by GenTxt** [jeffbinder/sentence-level-markov#2]
Hi jeff:

Thanks for interesting repo. I've generated the corpus but the training is causing errors which I suspect has to do with my non-AVX supported version of tensorflow/keras.  Max on my current system is tensorflow 1.5 (gpu) under python 3.6.5 because of my older cpu.   

Which versions of tf works with your scripts?

Thanks,

P.S. Time for a New Year cpu upgrade

**Comment by jeffbinder** [comment]
Thanks for your interest!  I have been using TensorFlow version 1.12.0 with Python 3.6.4.  I'm not really sure how far back you can go before the scripts will stop working.  AVX support doesn't matter as far as I know.

**Comment by GenTxt** [comment]
Thanks. That would explain it.  Tensorflow added the AVX requirement from
1.6 on so any standard install fails when AVX isn't detected in cpu.
Only recommended solution is to build from sources and hope it works.  I'll
try building 1.12 and see what happens.

Enjoy the holidays

**Comment by GenTxt** [comment]
Hi: Managed to find a custom .whl version of tf 1.12 that runs under ubuntu 18.04 and python 3.6.5 on my machine using the gtx 1070. I've completed steps 1 and two as per your readme and generated both the required corpus and network files. 

When I execute step 3: python markovize.py text.corpus text.network sample.txt sample.markov
it generates the following error:

Traceback (most recent call last):
  File "markovize.py", line 80, in <module>
    sentences = [text[0:spans[0][1]]]    
TypeError: 'generator' object is not subscriptable

Any suggestion on how to fix? I've tried several changes but only managed to reproduce "sample.txt" as "sample.markov" verbatim minus the paragraph breaks. Perhaps the above works because you're running under Anaconda?

Thanks

**Comment by jeffbinder** [comment]
I'm not using Anaconda. I would guess this is caused by an incompatible version of NLTK. Is the tokenizer producing a generator rather than a list? If so, you could probably solve the problem by adding "spans = list(spans)" on the line before the line that gets the error. That's an inefficient way to do it, but it probably wouldn't make much of a difference. Let me know if that fixes it and I will change the code.

**Comment by GenTxt** [comment]
Thanks for the update. Appears to be working now although the markovize.py script is very slow processing a 50k word sample.txt. The initial preparation/training were fast and converted a merged 8.3 meg text file to a 28.3 meg corpus and a 5.9 meg network.

This is the current terminal output after 3 hours running on gpu:
80 / 4762
Sentence:  He ought to know I'd come in some place like this and wait for him."
Generated next sentence: "I don't know." she said.
Actual next sentence: 
"He probably had an accident," she said.

I assume script must process 4762 sentences before generating sample.markov?

Revised markovize.py snippet:

tknzr = nltk.tokenize.punkt.PunktSentenceTokenizer()
spans = tknzr.span_tokenize(text)
spans = list(spans)
sentences = [text[0:spans[0][1]]]
etc.

Cheers

**Comment by jeffbinder** [comment]
I pushed the fix.

Unfortunately the Markovize script will always be slow because it has to run the decoder RNN for every pair of sentences in the input (not just every individual sentence).  This is why I split Moby-Dick into individual chapters for my experiment.  There are other ways of setting up the model that would be more efficient, but I haven't come up with one that works as well as the present method.

If you want to test it out quickly, you can edit the NUM_SENTENCES variable in markovize.py to make it use only the first n sentences in the document.

**Comment by GenTxt** [comment]
Thanks. A chapter-by-chapter approach is the way to go. Everything working so I'll close this now.
Cheers
